name: Check format & lint
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
env:
  PRJ_ENV_ID: tengencho-dev
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  check-format-lint:
    name: AWS deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Cache CDK Dependency
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Setup Node.js
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: npx pnpm i
      - name: Check format & lint
        env:
          NEXT_PUBLIC_BASE_URL: https://d3fb068sqi1zbm.cloudfront.net
        run: |
          echo "AWS_ROLE_ARN=${AWS_ROLE_ARN}" >> .env.local
          echo "NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}" >> .env.local
          echo "NEXTAUTH_SECRET=${NEXT_AUTH_SECRET}" >> .env.local
          echo "NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}" >> .env.local
          echo ${FIREBASE_SECRET_KEY} > firebaseSecretKey.json
          npm run check:prettier
          npm run check:eslint
          rm .env.local
