name: Check format & lint AWS deployment
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
env:
  PRJ_ENV_ID: tengencho-dev
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  check-and-deploy:
    name: check with prettier & eslint, AWS deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Check format
        run: npm run check:prettier
      - name: Lint
        run: npm run check:eslint
      - name: Deploy
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          echo "AWS_ROLE_ARN=${AWS_ROLE_ARN}" >> .env.local
          make build
